---
- name: Install https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm
  ansible.builtin.yum:
    name: https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm
    state: present

- name: Install mysql-community-client for WP-CLI
  ansible.builtin.package:
    name: mysql-community-client
    state: present

- name: Create WordPress install directory
  ansible.builtin.file:
    dest: '{{ wp_install_path }}'
    state: directory
    owner: apache
    group: apache
    mode: 0755
    recurse: yes

- name: Retrieve WordPress and unarchive
  ansible.builtin.command:
    "sudo -u apache /usr/local/bin/wp core download
     --path={{ wp_install_path }}"
  register: wp_download
  changed_when: wp_download.stdout | length > 0
  ignore_errors: true

- name: Create and configure 'wp-config.php'
  ansible.builtin.command:
    "sudo -u apache /usr/local/bin/wp core config
     --dbname={{ db_name }}
     --dbuser={{ db_user }}
     --dbpass={{ db_password }}
     --dbhost={{ db_host }}
     --dbprefix={{ db_prefix }}"
  register: wp_config
  changed_when: wp_config.stdout | length > 0
  args:
    chdir: '{{ wp_install_path }}'

- name: Install WordPress
  ansible.builtin.command:
    "sudo -u apache /usr/local/bin/wp core install
     --url={{ wp_url }}
     --title={{ wp_title }}
     --admin_user={{ wp_admin_user }}
     --admin_password={{ wp_admin_password }}
     --admin_email={{ wp_admin_email }}
     --allow-root"
  register: wp_install
  changed_when: wp_install.stdout | length > 0
  args:
    chdir: '{{ wp_install_path }}'

- name: Install Japanese language kit
  ansible.builtin.command:
    "sudo -u apache /usr/local/bin/wp core language install ja"
  register: wp_lang_install
  changed_when: wp_lang_install.stdout | length > 0
  args:
    chdir: '{{ wp_install_path }}'

- name: Localize WordPress for Japanese
  ansible.builtin.command:
    "sudo -u apache /usr/local/bin/wp core language activate ja"
  register: wp_lang_localize
  changed_when: wp_lang_localize.stdout | length > 0
  args:
    chdir: '{{ wp_install_path }}'

- name: Copy "{{ httpd_conf_confd }} to '/etc/httpd/conf.d/'"
  ansible.builtin.file:
    path: "/etc/httpd/conf.d/{{ httpd_conf_confd }}"
    state: touch
    mode: 0644

- name: Enable .htaccess
  ansible.builtin.blockinfile:
    path: "/etc/httpd/conf.d/{{ httpd_conf_confd }}"
    block: |
      <Directory "{{ wp_install_path }}">
        AllowOverride All
      </Directory>

- name: Restart httpd
  ansible.builtin.service:
    name: httpd
    state: restarted
    enabled: yes
