---
version: 2.1

orbs:
  ansible-lint: orbss/ansible-lint@0.0.3
  aws-cli: circleci/aws-cli@3.1.1
  molecule-ec2: orbss/molecule-ec2@0.0.9
  yamllint: orbss/yamllint@0.0.4

jobs:
  ansible-lint:
    executor: ansible-lint/default
    steps:
      - checkout
      - ansible-lint/execute:
          molecule-role-test: true
  molecule:
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: medium
    parameters:
      ansible-user:
        type: string
      aws-ami-name:
        type: string
      aws-ami-owner-id:
        type: string
      aws-instance-type:
        type: string
      aws-resource-name:
        type: string
      aws-vpc-subnet-id:
        type: string
      circleci-timeout:
        type: string
      molecule-scenario-name:
        type: string
    working_directory: ~/wordpress_install
    steps:
      - checkout
      - aws-cli/setup
      - aws-cli/setup:
          profile-name: default
          role-arn: ${AWS_ROLE_ARN}
          role-session-name: << parameters.aws-resource-name >>
          session-duration: '2100'
      - run:
          name: Install Molecule and dependencies
          command: |
            pip3 install -r molecule/requirements.txt
      - molecule-ec2/execute:
          ansible-user: << parameters.ansible-user >>
          aws-ami-name: << parameters.aws-ami-name >>
          aws-ami-owner-id: << parameters.aws-ami-owner-id >>
          aws-instance-type: << parameters.aws-instance-type >>
          aws-resource-name: << parameters.aws-resource-name >>
          aws-vpc-subnet-id: << parameters.aws-vpc-subnet-id >>
          circleci-timeout: << parameters.circleci-timeout >>
          molecule-scenario-name: << parameters.molecule-scenario-name >>
      - store_artifacts:
          path: molecule/<< parameters.molecule-scenario-name >>/files/screenshot.png
          destination: screenshot.<< parameters.molecule-scenario-name >>.png
  trailing-whitespace:
    docker:
      - image: ghcr.io/docker-images-mamono210/circleci-executors/trailing-whitespace:latest
    resource_class: small
    steps:
      - checkout
      - run:
          name: Execute trailing-whitespace
          command: trailing-whitespace
  yamllint:
    executor: yamllint/default
    steps:
      - checkout
      - yamllint/execute

workflows:
  version: 2.1
  build:
    jobs:
      - trailing-whitespace
      - yamllint:
          requires:
            - trailing-whitespace
      - ansible-lint:
          requires:
            - yamllint
      - molecule:
          ansible-user: 'ec2-user'
          aws-ami-name: 'centos-stream9-1*'
          aws-ami-owner-id: '808683561341'
          aws-instance-type: 't2.medium'
          aws-resource-name: 'circleci_ansible-roles_wordpress_install_cs9'
          aws-vpc-subnet-id: 'subnet-022a704b3061b8b39'
          circleci-timeout: '15m'
          molecule-scenario-name: 'default'
          context: 'aws-oidc'
          requires:
            - ansible-lint
