---
version: 2.1

orbs:
  ansible-lint: orbss/ansible-lint@0.0.3

jobs:
  ansible-lint:
    executor: ansible-lint/default
    steps:
      - checkout
      - ansible-lint/execute:
          molecule-role-test: true
  molecule:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
    parameters:
      checkout-path:
        type: string
      molecule-test-image:
        type: string
    steps:
      - checkout:
          path: << parameters.checkout-path >>
      - run:
          name: Install Molecule and dependencies
          command: |
            cd << parameters.checkout-path >>
            pip3 install -r molecule/requirements.txt
      - run:
          name: Test with Molecule
          command: |
            cd << parameters.checkout-path >>
            molecule test --scenario-name << parameters.molecule-test-image >>
          environment:
            PY_COLORS: '1'
            ANSIBLE_FORCE_COLOR: '1'
            MOLECULE_IMAGE: "ghcr.io/docker-images-mamono210/ansible-test/<< parameters.molecule-test-image >>:latest"
      - store_artifacts:
          path: << parameters.checkout-path >>/molecule/<< parameters.molecule-test-image >>/files/screenshot.png
          destination: screenshot.<< parameters.molecule-test-image >>.png
      - run:
          name: Show Ansible version
          command: |
            pip3 list | grep ansible \
            | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
            | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
            | GREP_COLORS='mt=01;33' egrep --color=always 'ansible.* '
      - run:
          name: Show Molecule version
          command: molecule --version
  trailing-whitespace:
    docker:
      - image: ghcr.io/docker-images-mamono210/circleci-executors/trailing-whitespace:latest
    resource_class: small
    steps:
      - checkout
      - run:
          name: Execute trailing-whitespace
          command: trailing-whitespace
  yamllint:
    docker:
      - image: ghcr.io/docker-images-mamono210/circleci-executors/yamllint:latest
    resource_class: small
    steps:
      - checkout
      - run:
          name: Execute yamllint
          command: yamllint *
      - run:
          name: Show yamllint version
          command: |
            yamllint --version \
            | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
            | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
            | GREP_COLORS='mt=01;33' egrep --color=always 'yamllint.* '

workflows:
  version: 2.1
  build:
    jobs:
      - trailing-whitespace
      - yamllint:
          requires:
            - trailing-whitespace
      - ansible-lint:
          requires:
            - yamllint
      - molecule:
          matrix:
            parameters:
              checkout-path:
                - 'wordpress_install'
              molecule-test-image:
                - 'centos7'
                - 'centos-stream8'
          requires:
            - ansible-lint
