---
- name: Converge
  hosts: all
  become: true

  tasks:
    - name: Set variables of molecule.yml to molecule_platforms
      ansible.builtin.set_fact:
        molecule_platforms: "{{ molecule_yml.platforms }}"

    - name: Execute
      ansible.builtin.include_role:
        name: wordpress_install
      vars:
        image: "{{ molecule_platforms.0.image }}"
        instance_type: "{{ molecule_platforms.0.instance_type }}"
        keypair_name: "{{ molecule_platforms.0.keypair_name }}"
        resource_state: 'present'
        security_group_name: "{{ molecule_platforms.0.security_group_name }}"
        tag_name: "{{ molecule_platforms.0.tag_name }}"
        tag_created_by: "{{ molecule_platforms.0.tag_created_by }}"
        volume_size: "{{ molecule_platforms.0.volume_size }}"
        vpc_subnet_id: "{{ molecule_platforms.0.vpc_subnet_id }}"
