---
- name: Destroy
  hosts: localhost
  connection: local

  tasks:
    - name: set_fact molecule_platforms
      ansible.builtin.set_fact:
        molecule_platforms: "{{ molecule_yml.platforms }}"

    - name: Remove WordPress container
      community.docker.docker_container:
        name: "{{ molecule_platforms.0.name }}"
        state: absent

    - name: Remove MySQL container
      community.docker.docker_container:
        name: "{{ molecule_platforms.1.name }}"
        state: absent

    - name: Delete a network
      community.docker.docker_network:
        name: "{{ molecule_platforms.0.networks }}"
        state: absent
        force: yes
