---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: wordpress
    image: ${MOLECULE_IMAGE}
    command: /sbin/init
    detach: yes
    networks:
      - name: molecule_wordpress
    privileged: yes
    ports:
      - "80:80"
    state: started
    tty: yes
  - name: db
    image: mysql:5.7
    networks: molecule_wordpress
    env:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  - name: selenium
    image: selenium/standalone-firefox:latest
    networks:
      - name: molecule_wordpress
    ports:
      - "4444:4444"
    state: started
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
  connection_options:
    wp_host: 'wordpress'
    php_packages:
      - php
      - php-gd
      - php-gmp
      - php-intl
      - php-ldap
      - php-mbstring
      - php-mcrypt
      - php-mysqlnd
      - php-opcache
      - php-pdo
      - php-pear
      - php-pear-Net-Curl
      - php-pecl-apcu-bc
      - php-pecl-redis
      - php-pecl-zip
      - php-soap
      - php-xml
verifier:
  name: ansible
scenario:
  converge_sequence:
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - dependency
    - syntax
    - create
    - converge
    - verify
    - destroy
