---
- name: Side effect
  gather_facts: false
  hosts: localhost

  tasks:
    - name: Execute selenium
      ansible.builtin.command:
        cmd: python screenshot.py
      args:
        chdir: files
      changed_when: false
      delegate_to: localhost
