---
- name: Verify
  become: true
  hosts: all

  tasks:
    - name: Gather facts
      ansible.builtin.setup:
      register: results
      delegate_to: localhost

    - name: Populate instance config
      ansible.builtin.set_fact:
        instance_conf: "{{ lookup('file', molecule_instance_config) | from_yaml }}"

    - name: Set fact for Public IP
      ansible.builtin.set_fact:
        public_ip: "{{ item.address }}"
      with_items: "{{ instance_conf }}"

    - name: Write Public IP to a file
      ansible.builtin.copy:
        content: "{{ public_ip }}"
        dest: /tmp/ip_address.txt
        mode: preserve
      delegate_to: localhost

    - name: Set WordPress URL
      ansible.builtin.command:
        cmd:
          "sudo -u apache /usr/local/bin/wp search-replace
           {{ wp_url }}
           http://{{ public_ip }}/{{ wp_install_dir }}
           --all-tables
           --allow-root"
      register: wp_config
      changed_when: wp_config.stdout | length > 0
      args:
        chdir: '{{ wp_install_path }}'

    - name: Reload httpd
      ansible.builtin.systemd_service:
        name: httpd.service
        state: reloaded

    - name: Set SELinux to Permissive mode.
      ansible.posix.selinux:
        state: permissive
        policy: targeted

    - name: Execute selenium
      ansible.builtin.command:
        cmd: "{{ results.ansible_facts.ansible_python.executable }} screenshot.py"
      args:
        chdir: files
      changed_when: false
      delegate_to: localhost

    - name: Check whether PHP installed
      ansible.builtin.command: php -v
      register: php_installed
      changed_when: false

    - name: Check whether WP-CLI installed
      ansible.builtin.command: |
        sudo -u apache /usr/local/bin/wp cli version
      register: wpcli_installed
      changed_when: false

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Make sure PHP is installed
      ansible.builtin.debug:
        var: php_installed

    - name: Make sure WP-CLI is installed
      ansible.builtin.debug:
        var: wpcli_installed

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
