---
- name: Converge
  hosts: wordpress
  connection: docker
  become: true
  vars:
    ansible_user: ansible
  roles:
    - role: geerlingguy.repo-epel
    - role: geerlingguy.repo-remi
    - role: mamono210.php
    - role: mamono210.wp_cli
    - role: mamono210.mysql_client
    - role: wordpress_install
