---
- name: Converge
  hosts: wordpress
  connection: docker
  become: true
  vars:
    ansible_user: ansible
  roles:
    - role: mamono210.epel
    - role: mamono210.remi
    - role: mamono210.php
    - role: mamono210.wp_cli
    - role: mamono210.mysql_client
    - role: wordpress_install
